//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonferHealth.Server.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PathwayStage
    {
        public PathwayStage()
        {
            this.PathwayStageOrganisations = new HashSet<PathwayStageOrganisation>();
        }
    
        [Key]
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public string Description { get; set; }
        public string Tag { get; set; }
        public Nullable<System.Guid> PathwayID { get; set; }
    
        public virtual Pathway Pathway { get; set; }
        public virtual ICollection<PathwayStageOrganisation> PathwayStageOrganisations { get; set; }
    }
}
